export const ProjectsFormStruct = {
	main: [
		{
			type: "settings",
			position: "label-left",
			labelWidth: 110,
			inputWidth: 220,
			offsetTop: 10,
			offsetLeft: 10,
		},
        { type: "hidden", name: "level", label: "Level" },
        { type: "input", name: "title", label: "Name", required: true },
		{
			type: "button",
			name: "submit",
			value: "Submit",
			width: "62",
			className: "",
			inputWidth: 60,
			offsetLeft: 150,
		},
	],
	sub: [
		{
			type: "settings",
			position: "label-left",
			labelWidth: 110,
			inputWidth: 220,
			offsetTop: 10,
			offsetLeft: 10,
		},
        { type: "hidden", name: "level", label: "Level" },
        { type: "hidden", name: "parent_id", label: "Parent" },
        { type: "input", name: "title", label: "Name", required: true },
		{
			type: "button",
			name: "submit",
			value: "Submit",
			width: "62",
			className: "",
			inputWidth: 60,
			offsetLeft: 150,
		},
	],
	update: [
		{
			type: "settings",
			position: "label-left",
			labelWidth: 110,
			inputWidth: 220,
			offsetTop: 10,
			offsetLeft: 10,
		},
        { type: "input", name: "item_name", label: "New Name", required: true },
		{
			type: "button",
			name: "submit",
			value: "Submit",
			width: "62",
			className: "",
			inputWidth: 60,
			offsetLeft: 150,
		},
	],
};
